# Generated by Django 5.2.3 on 2025-06-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='basic_salary',
            new_name='allowance',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='net_pay',
            new_name='basic',
        ),
        migrations.RenameField(
            model_name='performancereview',
            old_name='reviewer',
            new_name='manager',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(default='Casual', max_length=50),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
