# Generated by Django 5.2.3 on 2025-07-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_payroll_bonus_alter_payroll_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='bonus',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='allowance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='basic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='deductions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='hra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.CharField(max_length=7),
        ),
    ]
