# Generated by Django 5.2.3 on 2025-07-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_payroll_bonus_alter_payroll_allowance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='allowance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='basic',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='deductions',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='hra',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.CharField(max_length=20),
        ),
    ]
