# Generated by Django 5.2.3 on 2025-06-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team_images/')),
                ('link', models.URLField(blank=True)),
                ('team', models.CharField(choices=[('frontend', 'Frontend Developers'), ('backend', 'Backend Developers'), ('qa', 'Quality Analysts')], max_length=50)),
            ],
        ),
    ]
