# Generated by Django 5.2.3 on 2025-06-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ourteams_ourwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteams',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='team_images/'),
        ),
        migrations.AlterField(
            model_name='ourteams',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
